### ISSUE TITLE
全民挖现金脚本助力无效

### ISSUE THREAD

**Issue by hdstar2009** [panghu999/panghu#2]
运行获得了邀请码，替换了脚本的邀请码，运行，并没有助力。
export shareCode="063ECB1A9646DE46BC734FA0F15BB6" 设置环境变量，运行，还是没有助力。
请问这个挖现金脚本是不是助力功能没有？

**Comment by 15991491954** [comment]
你不是 一个人

**Comment by VwEl** [comment]
你不是 一个人

**Comment by q07942** [comment]
我设置了也没有助力是咋回事~

**Comment by hdstar2009** [comment]
可以关issue了，作者tg群说过，这个脚本现在不行。
